---
title: "Make a heatmap with a set of genes"
author: "Mark & Izel"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    fig_width: 7
    fig_height: 7
theme: cosmo
---

# Intro

Make a heatmap with a pre-specified list of genes.


```{r,start}

library("gplots")

x <- read.table("https://ziemann-lab.net/public/craig_smith/rxfp3_ant/rxfp3_ant_counts.tsv",header=TRUE,sep="\t")
head(x)

rpm <- x/colSums(x) * 1000000
head(rpm)

#mygenelist <- sample(rownames(x),30)
#writeLines(mygenelist,"mygenelist.txt")

```

Read in the list of genes and make the heatmap.

```{r,readlist}

mygenelist <- readLines("mygenelist.txt")

rows <- which(rownames(rpm) %in% mygenelist)
rpm_subset <- rpm[rows,]

rownames(rpm_subset) <- sapply(strsplit(rownames(rpm_subset)," "),"[[",2)

str(rpm_subset)

colfunc <- colorRampPalette(c("blue", "white", "red"))

heatmap.2(as.matrix(rpm_subset),trace="none",col=colfunc(25),scale="row", 
  margins = c(10,6), cexRow=0.6,cexCol = 0.5, main="Selected genes"  )

```

## session information

```{r,session}

sessionInfo()

```